#include "include/static_api.h"
#include "static.h"
#include "structures.h"

#define OS_INT_T   .primitive = GC_INT,   .state = GC_UNCHECKED, .permanent = 1, .epoch = 0, .ref_count = 1
#define OS_BOOL_T  .primitive = GC_BOOL,  .state = GC_UNCHECKED, .permanent = 1, .epoch = 0, .ref_count = 1
#define OS_UNDEF_T .primitive = GC_UNDEF, .state = GC_UNCHECKED, .permanent = 1, .epoch = 0, .ref_count = 1

object OS_TRUE  = { OS_BOOL_T,  .data.integer = 1 };
object OS_FALSE = { OS_BOOL_T,  .data.integer = 0 };
object OS_UNDEF = { OS_UNDEF_T, .data.integer = 0 };
object OS_ZERO  = { OS_INT_T,   .data.integer = 0 };

object OS_PINTS[128] = {
    {OS_INT_T, .data.integer = 0  },
    {OS_INT_T, .data.integer = 1  }, {OS_INT_T, .data.integer = 2  },
    {OS_INT_T, .data.integer = 3  }, {OS_INT_T, .data.integer = 4  },
    {OS_INT_T, .data.integer = 5  }, {OS_INT_T, .data.integer = 6  },
    {OS_INT_T, .data.integer = 7  }, {OS_INT_T, .data.integer = 8  },
    {OS_INT_T, .data.integer = 9  }, {OS_INT_T, .data.integer = 10 },
    {OS_INT_T, .data.integer = 11 }, {OS_INT_T, .data.integer = 12 },
    {OS_INT_T, .data.integer = 13 }, {OS_INT_T, .data.integer = 14 },
    {OS_INT_T, .data.integer = 15 }, {OS_INT_T, .data.integer = 16 },
    {OS_INT_T, .data.integer = 17 }, {OS_INT_T, .data.integer = 18 },
    {OS_INT_T, .data.integer = 19 }, {OS_INT_T, .data.integer = 20 },
    {OS_INT_T, .data.integer = 21 }, {OS_INT_T, .data.integer = 22 },
    {OS_INT_T, .data.integer = 23 }, {OS_INT_T, .data.integer = 24 },
    {OS_INT_T, .data.integer = 25 }, {OS_INT_T, .data.integer = 26 },
    {OS_INT_T, .data.integer = 27 }, {OS_INT_T, .data.integer = 28 },
    {OS_INT_T, .data.integer = 29 }, {OS_INT_T, .data.integer = 30 },
    {OS_INT_T, .data.integer = 31 }, {OS_INT_T, .data.integer = 32 },
    {OS_INT_T, .data.integer = 33 }, {OS_INT_T, .data.integer = 34 },
    {OS_INT_T, .data.integer = 35 }, {OS_INT_T, .data.integer = 36 },
    {OS_INT_T, .data.integer = 37 }, {OS_INT_T, .data.integer = 38 },
    {OS_INT_T, .data.integer = 39 }, {OS_INT_T, .data.integer = 40 },
    {OS_INT_T, .data.integer = 41 }, {OS_INT_T, .data.integer = 42 },
    {OS_INT_T, .data.integer = 43 }, {OS_INT_T, .data.integer = 44 },
    {OS_INT_T, .data.integer = 45 }, {OS_INT_T, .data.integer = 46 },
    {OS_INT_T, .data.integer = 47 }, {OS_INT_T, .data.integer = 48 },
    {OS_INT_T, .data.integer = 49 }, {OS_INT_T, .data.integer = 50 },
    {OS_INT_T, .data.integer = 51 }, {OS_INT_T, .data.integer = 52 },
    {OS_INT_T, .data.integer = 53 }, {OS_INT_T, .data.integer = 54 },
    {OS_INT_T, .data.integer = 55 }, {OS_INT_T, .data.integer = 56 },
    {OS_INT_T, .data.integer = 57 }, {OS_INT_T, .data.integer = 58 },
    {OS_INT_T, .data.integer = 59 }, {OS_INT_T, .data.integer = 60 },
    {OS_INT_T, .data.integer = 61 }, {OS_INT_T, .data.integer = 62 },
    {OS_INT_T, .data.integer = 63 }, {OS_INT_T, .data.integer = 64 },
    {OS_INT_T, .data.integer = 65 }, {OS_INT_T, .data.integer = 66 },
    {OS_INT_T, .data.integer = 67 }, {OS_INT_T, .data.integer = 68 },
    {OS_INT_T, .data.integer = 69 }, {OS_INT_T, .data.integer = 70 },
    {OS_INT_T, .data.integer = 71 }, {OS_INT_T, .data.integer = 72 },
    {OS_INT_T, .data.integer = 73 }, {OS_INT_T, .data.integer = 74 },
    {OS_INT_T, .data.integer = 75 }, {OS_INT_T, .data.integer = 76 },
    {OS_INT_T, .data.integer = 77 }, {OS_INT_T, .data.integer = 78 },
    {OS_INT_T, .data.integer = 79 }, {OS_INT_T, .data.integer = 80 },
    {OS_INT_T, .data.integer = 81 }, {OS_INT_T, .data.integer = 82 },
    {OS_INT_T, .data.integer = 83 }, {OS_INT_T, .data.integer = 84 },
    {OS_INT_T, .data.integer = 85 }, {OS_INT_T, .data.integer = 86 },
    {OS_INT_T, .data.integer = 87 }, {OS_INT_T, .data.integer = 88 },
    {OS_INT_T, .data.integer = 89 }, {OS_INT_T, .data.integer = 90 },
    {OS_INT_T, .data.integer = 91 }, {OS_INT_T, .data.integer = 92 },
    {OS_INT_T, .data.integer = 93 }, {OS_INT_T, .data.integer = 94 },
    {OS_INT_T, .data.integer = 95 }, {OS_INT_T, .data.integer = 96 },
    {OS_INT_T, .data.integer = 97 }, {OS_INT_T, .data.integer = 98 },
    {OS_INT_T, .data.integer = 99 }, {OS_INT_T, .data.integer = 100},
    {OS_INT_T, .data.integer = 101}, {OS_INT_T, .data.integer = 102},
    {OS_INT_T, .data.integer = 103}, {OS_INT_T, .data.integer = 104},
    {OS_INT_T, .data.integer = 105}, {OS_INT_T, .data.integer = 106},
    {OS_INT_T, .data.integer = 107}, {OS_INT_T, .data.integer = 108},
    {OS_INT_T, .data.integer = 109}, {OS_INT_T, .data.integer = 110},
    {OS_INT_T, .data.integer = 111}, {OS_INT_T, .data.integer = 112},
    {OS_INT_T, .data.integer = 113}, {OS_INT_T, .data.integer = 114},
    {OS_INT_T, .data.integer = 115}, {OS_INT_T, .data.integer = 116},
    {OS_INT_T, .data.integer = 117}, {OS_INT_T, .data.integer = 118},
    {OS_INT_T, .data.integer = 119}, {OS_INT_T, .data.integer = 120},
    {OS_INT_T, .data.integer = 121}, {OS_INT_T, .data.integer = 122},
    {OS_INT_T, .data.integer = 123}, {OS_INT_T, .data.integer = 124},
    {OS_INT_T, .data.integer = 125}, {OS_INT_T, .data.integer = 126},
    {OS_INT_T, .data.integer = 127}
};

object OS_NINTS[128] = {
    {OS_INT_T, .data.integer =  0  },
    {OS_INT_T, .data.integer = -1  }, {OS_INT_T, .data.integer = -2  },
    {OS_INT_T, .data.integer = -3  }, {OS_INT_T, .data.integer = -4  },
    {OS_INT_T, .data.integer = -5  }, {OS_INT_T, .data.integer = -6  },
    {OS_INT_T, .data.integer = -7  }, {OS_INT_T, .data.integer = -8  },
    {OS_INT_T, .data.integer = -9  }, {OS_INT_T, .data.integer = -10 },
    {OS_INT_T, .data.integer = -11 }, {OS_INT_T, .data.integer = -12 },
    {OS_INT_T, .data.integer = -13 }, {OS_INT_T, .data.integer = -14 },
    {OS_INT_T, .data.integer = -15 }, {OS_INT_T, .data.integer = -16 },
    {OS_INT_T, .data.integer = -17 }, {OS_INT_T, .data.integer = -18 },
    {OS_INT_T, .data.integer = -19 }, {OS_INT_T, .data.integer = -20 },
    {OS_INT_T, .data.integer = -21 }, {OS_INT_T, .data.integer = -22 },
    {OS_INT_T, .data.integer = -23 }, {OS_INT_T, .data.integer = -24 },
    {OS_INT_T, .data.integer = -25 }, {OS_INT_T, .data.integer = -26 },
    {OS_INT_T, .data.integer = -27 }, {OS_INT_T, .data.integer = -28 },
    {OS_INT_T, .data.integer = -29 }, {OS_INT_T, .data.integer = -30 },
    {OS_INT_T, .data.integer = -31 }, {OS_INT_T, .data.integer = -32 },
    {OS_INT_T, .data.integer = -33 }, {OS_INT_T, .data.integer = -34 },
    {OS_INT_T, .data.integer = -35 }, {OS_INT_T, .data.integer = -36 },
    {OS_INT_T, .data.integer = -37 }, {OS_INT_T, .data.integer = -38 },
    {OS_INT_T, .data.integer = -39 }, {OS_INT_T, .data.integer = -40 },
    {OS_INT_T, .data.integer = -41 }, {OS_INT_T, .data.integer = -42 },
    {OS_INT_T, .data.integer = -43 }, {OS_INT_T, .data.integer = -44 },
    {OS_INT_T, .data.integer = -45 }, {OS_INT_T, .data.integer = -46 },
    {OS_INT_T, .data.integer = -47 }, {OS_INT_T, .data.integer = -48 },
    {OS_INT_T, .data.integer = -49 }, {OS_INT_T, .data.integer = -50 },
    {OS_INT_T, .data.integer = -51 }, {OS_INT_T, .data.integer = -52 },
    {OS_INT_T, .data.integer = -53 }, {OS_INT_T, .data.integer = -54 },
    {OS_INT_T, .data.integer = -55 }, {OS_INT_T, .data.integer = -56 },
    {OS_INT_T, .data.integer = -57 }, {OS_INT_T, .data.integer = -58 },
    {OS_INT_T, .data.integer = -59 }, {OS_INT_T, .data.integer = -60 },
    {OS_INT_T, .data.integer = -61 }, {OS_INT_T, .data.integer = -62 },
    {OS_INT_T, .data.integer = -63 }, {OS_INT_T, .data.integer = -64 },
    {OS_INT_T, .data.integer = -65 }, {OS_INT_T, .data.integer = -66 },
    {OS_INT_T, .data.integer = -67 }, {OS_INT_T, .data.integer = -68 },
    {OS_INT_T, .data.integer = -69 }, {OS_INT_T, .data.integer = -70 },
    {OS_INT_T, .data.integer = -71 }, {OS_INT_T, .data.integer = -72 },
    {OS_INT_T, .data.integer = -73 }, {OS_INT_T, .data.integer = -74 },
    {OS_INT_T, .data.integer = -75 }, {OS_INT_T, .data.integer = -76 },
    {OS_INT_T, .data.integer = -77 }, {OS_INT_T, .data.integer = -78 },
    {OS_INT_T, .data.integer = -79 }, {OS_INT_T, .data.integer = -80 },
    {OS_INT_T, .data.integer = -81 }, {OS_INT_T, .data.integer = -82 },
    {OS_INT_T, .data.integer = -83 }, {OS_INT_T, .data.integer = -84 },
    {OS_INT_T, .data.integer = -85 }, {OS_INT_T, .data.integer = -86 },
    {OS_INT_T, .data.integer = -87 }, {OS_INT_T, .data.integer = -88 },
    {OS_INT_T, .data.integer = -89 }, {OS_INT_T, .data.integer = -90 },
    {OS_INT_T, .data.integer = -91 }, {OS_INT_T, .data.integer = -92 },
    {OS_INT_T, .data.integer = -93 }, {OS_INT_T, .data.integer = -94 },
    {OS_INT_T, .data.integer = -95 }, {OS_INT_T, .data.integer = -96 },
    {OS_INT_T, .data.integer = -97 }, {OS_INT_T, .data.integer = -98 },
    {OS_INT_T, .data.integer = -99 }, {OS_INT_T, .data.integer = -100},
    {OS_INT_T, .data.integer = -101}, {OS_INT_T, .data.integer = -102},
    {OS_INT_T, .data.integer = -103}, {OS_INT_T, .data.integer = -104},
    {OS_INT_T, .data.integer = -105}, {OS_INT_T, .data.integer = -106},
    {OS_INT_T, .data.integer = -107}, {OS_INT_T, .data.integer = -108},
    {OS_INT_T, .data.integer = -109}, {OS_INT_T, .data.integer = -110},
    {OS_INT_T, .data.integer = -111}, {OS_INT_T, .data.integer = -112},
    {OS_INT_T, .data.integer = -113}, {OS_INT_T, .data.integer = -114},
    {OS_INT_T, .data.integer = -115}, {OS_INT_T, .data.integer = -116},
    {OS_INT_T, .data.integer = -117}, {OS_INT_T, .data.integer = -118},
    {OS_INT_T, .data.integer = -119}, {OS_INT_T, .data.integer = -120},
    {OS_INT_T, .data.integer = -121}, {OS_INT_T, .data.integer = -122},
    {OS_INT_T, .data.integer = -123}, {OS_INT_T, .data.integer = -124},
    {OS_INT_T, .data.integer = -125}, {OS_INT_T, .data.integer = -126},
    {OS_INT_T, .data.integer = -127}
};

object *O_TRUE  = &OS_TRUE;
object *O_FALSE = &OS_FALSE;
object *O_UNDEF = &OS_UNDEF;
object *O_ZERO  = &OS_ZERO;
object *O_PINTS = OS_PINTS;
object *O_NINTS = OS_NINTS;
